import './globals.css'
import Navbar from './components/navbar'
import Footer from './components/footer'
import Toast from './components/Toast'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-white">
        <Toast />
        <Navbar />
        <div className="container h-full max-w-7xl mx-auto mb-auto px-8">{children}
        </div>
        <Footer />
      </body>
    </html >
  )
}
